### ISSUE TITLE
Kernel Restarting

### ISSUE THREAD

**Issue by rkodag** [valeoai/ConfidNet#12]
The kernel for ConfidNet/confidnet/notebook/success_errors_histogram.ipynb appears to have died. It will restart automatically
![Screenshot from 2021-12-23 00-40-24](https://user-images.githubusercontent.com/88709180/147143403-549cfd6e-314d-41bd-9ecc-f3d19d472f73.png)
.

**Comment by chcorbi** [comment]
Hi @rkodag,

The `dloader` module wraps Pytorch's dataset into dataloader. Hence these lines shouldn't create memory issue. When checked on my side, it only adds ~0.30G in RAM. Maybe your computer RAM was already full?

Best,
Charles

**Comment by rkodag** [comment]
Thanks @chcorbi
