### ISSUE TITLE
Freeze Miniconda version and dependencies in Dockerfile

### ISSUE THREAD

**Issue by GirardR1006** [valeoai/ConfidNet#14]
Hello, for the Dockerfile to properly install the packages, I suggest to explicitly set the targeted Miniconda version:

Replace
`RUN wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh`
by
`RUN wget https://repo.anaconda.com/miniconda/Miniconda3-py37_4.12.0-Linux-x86_64.sh -O miniconda.sh`

Additionally, some dependencies must be explicitly specified:

`RUN pip install tensorflow==1.13.1 torchsummary pyyaml verboselogs coloredlogs click scikit-learn pillow==6.0.0 protobuf==3.20.0`

**Comment by chcorbi** [comment]
Hi @GirardR1006, thank you for pointing that out, I commited an update to fix it.
Best, 
Charles
