### ISSUE TITLE
OOD for?

### ISSUE THREAD

**Issue by GloryyrolG** [valeoai/ConfidNet#15]
Hi @chcorbi @nicothome @ab-h et al.,

Thanks for your great work. May I ask what OOD is here? Out-of-distribution?

https://github.com/valeoai/ConfidNet/blob/57d4a056adab1eb75f4a54c73422e60751ea3709/confidnet/learners/oodconfid_learner.py#L16

**Comment by chcorbi** [comment]
Hi @GloryyrolG 

OOD refers indeed to out-of-distribution. OODConfidLearner was an older test to evaluate joint training of the main task and the auxiliary confidence learning task. It is now deprecated.
