### ISSUE TITLE
CamVid dataset train / val / test split

### ISSUE THREAD

**Issue by YingdaXia** [valeoai/ConfidNet#5]
Hello authors,

After downloading CamVid data set from the link in your repo, we got 101 images with labels. How do you split train / val / test data? Could you please share your list so that I can reproduce your results? Thanks in advance for your help!

Best,
Yingda

**Comment by chcorbi** [comment]
Hi @YingdaXia,

I've seen that I didn't put the correct link, I apologize for the inconvenience. 
README have now been updated (#e6469ad) with the right one:
https://github.com/alexgkendall/SegNet-Tutorial/tree/master/CamVid

Following Kendall's standard implementation, CamVid dataset is split in:
- 367 training images
- 101 val images
- 233 test images

**Comment by YingdaXia** [comment]
Thank you for your information!
