### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by wusj0723** [valeoai/ConfidNet#9]
An error occurred while running the train.py file: "ModuleNotFoundError: No module named 'structured_map_ranking_loss' "

**Comment by chcorbi** [comment]
Hi @wusj0723,

Did you install the repo via `pip install -e ConfidNet`? The `pip` installation is much easier to work on.

Else, if you want to use the repo manually, you should first run `python3 setup.py install`, which include the compilation of the c++ file.
